# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27ee686bf8b27ade44e70e85b1aad5c7c8f4c35cb698693f234f65c623c3e508d2b632ae248dbd3c535cbff582e4a90b33e427e5e060896d2ff8e258e0acc564

test:
  secret_key_base: 437b419f4df14c067663470323ed33627800f1d3677d4e04730a58dafbe2055f405399e59a111558ac8ce94dca72104ca11321c0b75410308f1cf64e1ff1fc75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
